### PR TITLE
Hapi 17

### PR DESCRIPTION
**Pull request by superdav42**
This pulls latest changes from upstream and tweaks the code to work with hapi v17.

### CODE REVIEW

**Comment by c-shultz** [comment]
@superdav42, any suggestions for how to test this one locally? 

Do you think this will break backwards compatibility with older versions of hapi? I just ask because we may want to keep that in mind if we need to roll back the Connect Server change and would then need to roll this back too.

**Comment by superdav42** [comment]
> @superdav42, any suggestions for how to test this one locally?

`npm run test`? Actually see below.


> Do you think this will break backwards compatibility with older versions of hapi? I just ask because we may want to keep that in mind if we need to roll back the Connect Server change and would then need to roll this back too.

In that case think it might be best just to leave this as a separate branch. It's possible to tell npm to use a specific branch so we'll just do that for now until we are confident things will work. 

So update the package.json require statement to `"hapi-statsd": "github:Automattic/hapi-statsd#hapi-17",` and then make sure statsd is being triggered in our app as it should be. I'm working an a unit test for it too.

**Comment by superdav42** [comment]
Closing this PR in favor of keeping the changes in a separate branch. Connect server can use this branch as is without it needing to be merged.

**Comment by c-shultz** [comment]
That sounds good! We can merge and point back to master after this is tested in production

**Comment by harriswong** [comment]
👋 Hi @c-shultz, we are at this time again to upgrade Hapi to 21 and I come across this. I am planning to branch off the Hapi v21 work off this branch and merge that directly to `master`. If it fails, then I will roll back to the `hapi-17` branch.

If all looks good, I will delete this branch since the new code will be in `master`.

**Pull request closed without merging**
